#!/bin/bash

check_gpumode=$(supergfxctl -g)

if [[ $check_gpumode == "AsusMuxDgpu" ]]; then
  cat >~/.config/hypr/conf/gpu-env.conf <<EOF
# NVIDIA Specific

# To force GBM as a backend, set the following environment variables
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Hardware acceleration on NVIDIA GPUs
env = LIBVA_DRIVER_NAME,nvidia

# VA-API hardware video acceleration
env = NVD_BACKEND,direct
env = cursor:no_hardware_cursors

# Controls if G-Sync capable monitors should use Variable Refresh Rate (VRR)
env = __GL_GSYNC_ALLOWED,

# Controls if Adaptive Sync should be used. Recommended to set as “0” to avoid having problems on some games.
env = __GL_VRR_ALLOWED,0

# Use legacy DRM interface instead of atomic mode setting. Might fix flickering issues.
env = WLR_DRM_NO_ATOMIC,1
EOF
else
  cat >~/.config/hypr/conf/gpu-env.conf <<EOF
# To tell Hyprland the GPU we want to use primarily.
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
EOF
fi
