#!/usr/bin/env sh

# Mevcut animasyon durumunu kontrol et
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

if [ "$HYPRGAMEMODE" = 1 ] ; then
    # OYUN MODU AÇILIYOR: Ayarları kapat/değiştir
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
        
    # Bildirim gönder: Mod Açıldı
    notify-send "Oyun Modu etkinleştirildi."
    exit
fi

# OYUN MODU KAPATILIYOR: Ayarları yeniden yükle
hyprctl reload

# Bildirim gönder: Mod Kapatıldı
notify-send "Oyun Modu devre dışı bırakıldı."

