# Example windowrule v1
# windowrule = float, ^(kitty)$
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(blueman-manager)$
windowrule = float, title:^(btop)$
windowrule = size 1200 800, title:^(btop)$
windowrule = center, title:^(btop)$
windowrule = float, title:^(update-sys)$
windowrule = size 1000 600, title:^(update-sys)$
windowrule = center, title:^(update-sys)$
windowrule = float, wofi
windowrule = float, title:^(Web Uygulamaları)$
windowrule = size 800 600, title:^(Web Uygulamaları)$
windowrule = float, title:^(Arkadaş Listesi)$
windowrule = float, title:^(Steam - Haberler)$
windowrule = float, title:^(movie.sh)$
windowrule = size 1400 600, title:^(movie.sh)$
windowrule = center, title:^(movie.sh)$

# Example windowrule v2
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$,title:^(Kimlik Doğrulama Gerekli — PolicyKit1 KDE Aracısı)$
windowrulev2 = animation popin,class:^(org.kde.polkit-kde-authentication-agent-1)$,title:^(Kimlik Doğrulama Gerekli — PolicyKit1 KDE Aracısı)$
windowrulev2 = animation popin,class:^(kitty)$,title:^(update-sys)$
windowrulev2 = opacity 1.0 0.9,class:^(Thunar)$
windowrulev2 = opacity 0.90 0.90,class:^(org.kde.dolphin)$
windowrulev2 = float, class:^(mpv)$
