# hyprpaper
wallpaper {
  monitor = DP-1
  path = $HOME/.local/state/wallpaper
  fit_mode =cover
}
# Eğer birden fazla monitörünüz varsa, her biri için bu satırı tekrar edin.

splash = false

# IPC ile komut göndermeyi etkinleştirir
ipc = yes 
