general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = ~/.config/scripts/razer stop; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on; ~/.config/scripts/razer start &
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10; openrgb -p pars-off
    on-resume = brightnessctl -r; openrgb -p pars-white
}

listener {
    timeout = 450
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on; brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
