general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pkill waybar; pkill openrazer-daemon; pkill -f razer-battery-tray; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on; sleep 1; waybar & sleep 2; openrazer-daemon -r & sleep 2; cd ~/.razer/RazerBatteryTray && uv run razer-battery-tray 'DeathStalker' &
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10 & openrgb -p pars-off
    on-resume = brightnessctl -r & openrgb -p pars-white
}

listener {
    timeout = 450
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = pkill waybar; pkill openrazer-daemon; pkill -f razer-battery-tray; hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r; sleep 1; waybar & sleep 2; openrazer-daemon -r & sleep 2; cd ~/.razer/RazerBatteryTray && uv run razer-battery-tray 'DeathStalker' &
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

