# Example windowrule
# windowrule = float, title:^(kitty)$
# windowrule = float, title:^(galculator)$
windowrule = match:class org.gnome.Calculator, float true
# Waydroid
windowrule = match:title Waydroid, fullscreen true
# Waypaper
windowrule {
  name = move-waypaper
  match:class = waypaper
  float = true
  size = 800 600
  move = 880 52
}
# Mpv
windowrule = match:class imv, float true
windowrule = match:class mpv, float true

# WebApps - Gemini
# windowrule = float, class:^(chrome-gemini.google.com__app-Default)$
# windowrule = size 1400 800, class:^(chrome-gemini.google.com__app-Default)$
