#!/bin/bash

gpumode=$(supergfxctl -g)
internalgpu=$(sensors -A amdgpu-pci-0600 | awk '/°C/ {print $2}' | cut -c2-3)
externalgpu=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)

if echo $gpumode | grep -q "Hybrid"; then 
  echo "{\"text\":\"I-GPU $internalgpu°C      E-GPU $externalgpu°C\", \"tooltip\":\"Hybrid\"}"
elif echo $gpumode | grep -q "Integrated";  then
  echo "{\"text\":\"GPU $internalgpu°C\", \"tooltip\":\"Integrated\"}"
elif echo $gpumode | grep -q "Vfio" ; then
  echo "{\"text\":\"Vfio\", \"tooltip\":\"Vfio\"}"
fi
